CREATE DATABASE IF NOT EXISTS quanlycuahang CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE quanlycuahang;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ChiTietHoaDon;
DROP TABLE IF EXISTS HoaDon;
DROP TABLE IF EXISTS SanPham;
DROP TABLE IF EXISTS TaiKhoan;
DROP TABLE IF EXISTS NhanVien;
DROP TABLE IF EXISTS KhachHang;
DROP TABLE IF EXISTS NhaCungCap;
DROP TABLE IF EXISTS LoaiSanPham;

CREATE TABLE LoaiSanPham (
  MaLoai VARCHAR(50) NOT NULL,
  TenLoai VARCHAR(255) NOT NULL,
  PRIMARY KEY (MaLoai)
) ENGINE=InnoDB;

CREATE TABLE NhaCungCap (
  MaNCC VARCHAR(50) NOT NULL,
  TenNCC VARCHAR(255) NOT NULL,
  DiaChi VARCHAR(255) NULL,
  Email VARCHAR(255) NULL,
  PRIMARY KEY (MaNCC)
) ENGINE=InnoDB;

CREATE TABLE KhachHang (
  MaKH VARCHAR(50) NOT NULL,
  TenKH VARCHAR(255) NOT NULL,
  SoDT VARCHAR(20) NULL,
  DiemTichLuy INT NOT NULL DEFAULT 0,
  PRIMARY KEY (MaKH)
) ENGINE=InnoDB;

CREATE TABLE NhanVien (
  MaNV VARCHAR(50) NOT NULL,
  HoTen VARCHAR(255) NOT NULL,
  NgaySinh DATE NULL,
  SoDT VARCHAR(20) NULL,
  ChucVu VARCHAR(100) NULL,
  PRIMARY KEY (MaNV)
) ENGINE=InnoDB;

CREATE TABLE TaiKhoan (
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Quyen VARCHAR(50) NOT NULL,
  MaNV VARCHAR(50) NULL,
  PRIMARY KEY (Username),
  CONSTRAINT FK_TaiKhoan_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE SanPham (
  MaSP VARCHAR(50) NOT NULL,
  TenSP VARCHAR(255) NOT NULL,
  GiaBan DOUBLE NOT NULL DEFAULT 0,
  DonViTinh VARCHAR(50) NULL,
  SoLuongTon INT NOT NULL DEFAULT 0,
  MaLoai VARCHAR(50) NULL,
  MaNCC VARCHAR(50) NULL,
  PRIMARY KEY (MaSP),
  CONSTRAINT FK_SanPham_LoaiSanPham FOREIGN KEY (MaLoai) REFERENCES LoaiSanPham(MaLoai)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT FK_SanPham_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE HoaDon (
  MaHD VARCHAR(50) NOT NULL,
  NgayLap DATETIME NOT NULL,
  TongTien DOUBLE NOT NULL DEFAULT 0,
  TrangThai VARCHAR(50) NOT NULL DEFAULT 'Pending',
  MaKH VARCHAR(50) NULL,
  MaNV VARCHAR(50) NULL,
  PRIMARY KEY (MaHD),
  CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE ChiTietHoaDon (
  MaCTHD INT NOT NULL AUTO_INCREMENT,
  MaHD VARCHAR(50) NOT NULL,
  MaSP VARCHAR(50) NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DOUBLE NOT NULL,
  PRIMARY KEY (MaCTHD),
  UNIQUE KEY UQ_ChiTietHoaDon_MaHD_MaSP (MaHD, MaSP),
  CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_ChiTietHoaDon_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE INDEX IDX_SanPham_MaLoai ON SanPham(MaLoai);
CREATE INDEX IDX_SanPham_MaNCC ON SanPham(MaNCC);
CREATE INDEX IDX_HoaDon_NgayLap ON HoaDon(NgayLap);
CREATE INDEX IDX_HoaDon_MaKH ON HoaDon(MaKH);
CREATE INDEX IDX_HoaDon_MaNV ON HoaDon(MaNV);
CREATE INDEX IDX_CTHD_MaHD ON ChiTietHoaDon(MaHD);
CREATE INDEX IDX_CTHD_MaSP ON ChiTietHoaDon(MaSP);

SET FOREIGN_KEY_CHECKS = 1;
